---
class: 8
flags: 0x0000
unid: OF3E03088055ABB9DA-ON0018A2A78525745F
items:
  - name: $COLLATION
    type_num: 2
    type: opaque
    opaque: BgAAAABE
  - name: $Comment
    type: text
    data: ""
    signed: true
  - name: $DesignerVersion
    type: text
    data: "7"
    signed: true
  - name: $FORMULA
    type: formula
    data: " (form = \"xpConfigProfile\")"
    opaque: |
      tAACACAACQBJbWFnZVRleHQABQAJAEltYWdlVGV4dAADAAIAIAAKAEZvb3RlclRleHQFAAoARm9vdGVy
      VGV4dAMABQA6ADYABAAOAAkACgAJAEF0dGFjaG1lbnROYW1lSW1hZ2VUZXh0Rm9vdGVyVGV4dCRDb25m
      bGljdAQABAAAACYABQAEAGZvcm0BAA8AeHBDb25maWdQcm9maWxlAAoCBAADAAcADgAIAAlMMVMzUzRT
    signed: true
  - name: $FORMULACLASS
    type: text
    data: "1"
    signed: true
  - name: $Flags
    type: text
    data: Y
  - name: $Index
    type: text
    data: ""
    signed: true
  - name: $LANGUAGE
    type: text
    data: en
    signed: true
  - name: $TITLE
    type: text
    data: ($xpConfigProfile)|xpConfigProfile
    signed: true
  - name: $VIEWFORMAT
    type_num: 5
    type: opaque
    opaque: |
      AQADADQAjgwAAFZDAAAOAA4AAAAAAHgAAQAACQAAAAAAAAAAAAICAAAAVkMAAAkACQAiAAAAeAABAAAK
      AAAAAAAAAAAAAgIAAABWQwAACgAKACIAAADwAAEAAAoAAAAAAAAAAAACAgAAAEF0dGFjaG1lbnROYW1l
      QXR0YWNobWVudE5hbWVJbWFnZVRleHRJbWFnZVRleHQiAAIAIAAJAEltYWdlVGV4dAAFAAkASW1hZ2VU
      ZXh0AAMARm9vdGVyVGV4dEZvb3RlclRleHQiAAIAIAAKAEZvb3RlclRleHQFAAoARm9vdGVyVGV4dAMA
      JgABAAAAAQEACQEACAoBAQQKAAA/AK0rAgABAAEAAAAAAAAAAABXQwEAAAkAAAAAAAAAAAAAAAAAAAAA
      AQAEAAAAAAD//wAAAAAAAAAAAAAAAAAAV0MBAAAJAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAA//8AAAAA
      AAAAAAAAAAAAAFdDAQAACQAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAP//AAAAAAAAAAAAAAAAAABCAAAA
      AAABAP///wABAO/v7wABAAAAAAAAAAAAAAABAAEA////AAEAtNXFAAAAAQCAAAAAAQAAAP8AAQAAAAAA
      AAAIAAAAAAABAA==
    signed: true
  - name: $WebFlags
    type: text
    data: YS
    signed: true
  - name: $V5ACTIONS
    type: composite
    signed: true
    nonsummary: true
    data:
      - type: 0x00bd
        BackColor: 15
        BorderStyle: 0
        BorderWidth: 0
        BtnHeight: 8
        FontID: 0x00000000
        HeightSpc: 0
        LineColor: 0
        LineStyle: 1
        ShareID: 0x00000000
        dwFlags: 0x00000000
      - type: 0xff79
        BackColor:
          Flags: 0x0001
          rgb: 0xc0c0c0
        BtnBorderDisplay: 0
        BtnTextJustify: 0
        BtnWidthStyle: 0
        ButtonColor:
          Flags: 0x0001
          rgb: 0xc0c0c0
        FontColor:
          Flags: 0x0001
          rgb: 0x000000
        LineColor:
          Flags: 0x0001
          rgb: 0x000000
        Spare:
          - 0x00000000
          - 0x00000000
          - 0x00000000
          - 0x00000000
          - 0x00000000
          - 0x00000000
          - 0x00000000
          - 0x00000000
          - 0x00000000
          - 0x00000000
          - 0x00000000
        barFontID: 0x00000000
        barHeight:
          Flags: 0x0000
          Length:
            - 0
            - 0
            - 0
            - 0
            - 0
            - 0
            - 0
            - 0
          Reserved: 0
          Units: 0
        dwFlags: 0x00000003
        wAppletHeight: 31
        wBarBackgroundRepeat: 0
        wBtnInternalMargin: 0
        wBtnWidthAbsolute: 0
        wSpare: 0x0000
        wThemeSetting: 0
      - type: 0xfffc
        BorderFlags: 0
        BorderStyle: 1
        BorderWidthBottom: 1
        BorderWidthLeft: 0
        BorderWidthRight: 0
        BorderWidthTop: 0
        Color:
          Flags: 0x0005
          rgb: 0xffffff
        DropShadowWidth: 0
        Flags: 0x00000000
        InnerWidthBottom: 0
        InnerWidthLeft: 0
        InnerWidthRight: 0
        InnerWidthTop: 0
        OuterWidthBottom: 0
        OuterWidthLeft: 0
        OuterWidthRight: 0
        OuterWidthTop: 0
        dwSpare: 0x00000000
        wSpares:
          - 0x0000
          - 0x0000
          - 0x0000
          - 0x0000
          - 0x0000
remaining: []