---
class: 4
flags: 0x0000
unid: OF97A57AD6ED99D617-ON002F0ED185258432
items:
  - name: $DesignerVersion
    type: text
    data: 8.5.3
    signed: true
  - name: $FileNames
    type: text
    data: Notes Discussion Application.xml
    signed: true
  - name: $Flags
    type: text
    data: 34567C|Q
  - name: $FlagsExt
    type: text
    data: "1"
    signed: true
  - name: $TITLE
    type: text
    data: Notes Discussion Application.xml
  - name: $FileData
    type: composite
    signed: true
    nonsummary: true
remaining: []