---
class: 4
flags: 0x0000
unid: OF2EAEEBBDC2EF2160-ON003BF04185258719
items:
  - name: $DesignerVersion
    type: text
    data: 8.5.3
    signed: true
  - name: $FileNames
    type: text
    data: ".classpath"
    signed: true
  - name: $Flags
    type: text
    data: ~C4g
  - name: $Revisions
    type: time
    data: "2021-07-21T06:54:41.53-04:00"
    dst: true
  - name: $TITLE
    type: text
    data: ".classpath"
  - name: $FileData
    type: composite
    signed: true
    nonsummary: true
remaining: []